version: '3.8'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: java_training
      MYSQL_USER: training
      MYSQL_PASSWORD: training
    volumes:
      - java_training_db:/var/lib/mysql

  eureka-server:
    image: openjdk:11-jdk
    working_dir: /app
    environment:
      HOST: eurekas-server
    volumes:
      - java-training-eureka-gradle-cache:/root/.gradle
      - ./eureka:/app
    command: ./gradlew clean bootRun

  email-client:
    image: openjdk:11-jdk
    working_dir: /app
    volumes:
      - java-training-email-gradle-cache:/root/.gradle
      - ./email:/app
    environment:
      CONFIG_SERVER_HOST: config-server
      EUREKA_HOST: eureka-server
    command: ./gradlew clean bootRun
    depends_on:
      - db

  gateway:
    image: openjdk:11-jdk
    working_dir: /app
    volumes:
      - java-training-gateway-gradle-cache:/root/.gradle
      - ./gateway:/app
    environment:
      CONFIG_SERVER_HOST: config-server
      EUREKA_HOST: eureka-server
    command: ./gradlew clean bootRun
    depends_on:
      - eureka-server
    ports:
      - 8088:8088

  config-server:
    image: openjdk:11-jdk
    working_dir: /app
    volumes:
      - java-training-config-gradle-cache:/root/.gradle
      - ./config-server:/app
    environment:
      PASSWORD: 52f234b951cbd1ba634122850e57df9074e6934a
    command: ./gradlew clean bootRun
    depends_on:
      - eureka-server

  user-client:
    image: openjdk:11-jdk
    working_dir: /app
    volumes:
      - java-training-user-gradle-cache:/root/.gradle
      - ./user:/app
    environment:
      CONFIG_SERVER_HOST: config-server
      EUREKA_HOST: eureka-server
      CONFIG_PROFILE: docker
    command: ./gradlew clean bootRun
    depends_on:
      - db
      - config-server

volumes:
  java_training_db:
    external: true
  java-training-user-gradle-cache:
    external: true
  java-training-gateway-gradle-cache:
    external: true
  java-training-erur-gradle-cache:
    external: true
  java-training-eureka-gradle-cache:
    external: true
  java-training-email-gradle-cache:
    external: true
  java-training-config-gradle-cache:
    external: true
