spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tiasen/java_training_config.git
          search-paths:
            - email
            - user
            - gateway
          username: tiasen
          password: ${PASSWORD}
        default-profile: dev
server:
  port: 7000
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:8180/eureka/
